name: 自动发布

on:
  push:
    branches:
      - main
      - fix/*

jobs:
  version-and-upload:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出代码
      - name: Checkout Code
        uses: actions/checkout@v6

      # 步骤2：设置pnpm环境
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      # 步骤3：安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 步骤4：自动更新版本号
      - name: Auto Update Version
        id: version
        run: |
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="${DATE}.${SHORT_SHA}"
          echo "版本号已更新至 $VERSION"
          echo "new_version=$VERSION" >> "$GITHUB_OUTPUT"

      # 步骤5：构建小程序代码
      - name: Build Mini Program
        run: pnpm build

      # 步骤5：获取最新commit message
      - name: Get Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: create private key file
        run: echo "$WECHAT_UPLOAD_KEY" > private.key
        env:
          WECHAT_UPLOAD_KEY: ${{ secrets.WECHAT_UPLOAD_KEY }}

      # 步骤6：上传到微信小程序
      - name: Upload to WeChat
        run: |
          npx miniprogram-ci upload --appid ${{ secrets.MINI_APP_ID }} --pp ./dist/wx --pt miniProgram --uv ${{ steps.version.outputs.new_version }} --pkp ./private.key
